version: '3.8'

services:
  app:
    build: .
    ports:
      - "3060:3000"
    environment:
      - DATABASE_URL=file:/app/data/prod.db
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NODE_ENV=production
    volumes:
      - app_data:/app/data
      - app_logs:/app/logs
    depends_on:
      - db-init
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db-init:
    build: .
    command: sh -c "npx prisma db push && npx prisma db seed"
    environment:
      - DATABASE_URL=file:/app/data/prod.db
    volumes:
      - app_data:/app/data
    restart: "no"

  # Nginx 反向代理 (可选)
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - app_logs:/var/log/nginx
  #   depends_on:
  #     - app
  #   restart: unless-stopped

volumes:
  app_data:
  app_logs: