version: '3.8'

services:
  app:
    build: .
    ports:
      - "3060:3000"
    environment:
      - DATABASE_URL=file:/app/data/dev.db
      - NEXTAUTH_SECRET=your-secret-key-change-in-production
    volumes:
      - app_data:/app/data
    depends_on:
      - db-init
    restart: unless-stopped

  db-init:
    build: .
    command: sh -c "ls -la prisma/ && npx prisma db push && npx prisma db seed"
    environment:
      - DATABASE_URL=file:/app/data/dev.db
    volumes:
      - app_data:/app/data
    restart: "no"

volumes:
  app_data: